#!/usr/bin/env	python

import sys

for line in sys.stdin:
	parts = line.rstrip().split('\t')
	regulator = parts[0]
	for gene in parts[1:len(parts)]:
		link = None
		try:
			float(gene)
			continue
		except:
			# do nothing
			link = '-t>'
		print '\t'.join([regulator, link, gene])
